name: cord19
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  - pip
  - python=3.6.5
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - ipython
  - pandas-gbq
  - plotly
  - nltk
  - gensim
  - altair
  - sklearn
  - umap-learn
  - statsmodels
  
  # Put any conda dependencies here

  - pip:
    - ratelim
    - markdown
    - bs4
    - html2text
    # Put any pip dependencies here (and no conda ones anywhere below)

  # Tooling requirements (don't edit)
    - tqdm
    - pyyaml
    - tables
    - black
    - blackcellmagic
    - pymysql
    - sqlalchemy
    - click
    - Sphinx
    - sphinxcontrib.napoleon
    - coverage
    - awscli
    - flake8
  - python-dotenv>=0.5.1
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jq
  - pytest
